package org.ridewithus.domain.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "bikes")
public class Bike {
    @Id //primary key 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by Database, not through constructors
    private Long id;

    private String status;
    private String type ;

    @ManyToOne
    @JoinColumn(name = "dock_id", unique = true) //unique makes it so it has acts as One-to-one relationship, more flexible for later on
    private Dock dock;

    public Bike() {
    }

    public Bike(String status, String type, Dock dock) {
        this.status = status;
        this.type = type;
        this.dock = dock;
    }

    // Getters 
    public Long getId(){ 
        return id; 
    }
    public String getStatus(){ 
        return status; 
    }
    

    public String getType(){ 
        return type; 
    }
    public Dock getDock(){ 
        return dock; 
    }
   
    // Setters
    public void setId(Long id){ 
        this.id = id; 
    }
    public void setStatus(String status){ 
        this.status = status; 
    }
    public void setType(String type){ 
        this.type = type; 
    }
    public void setDock(Dock dock){ 
        this.dock = dock; 
    }
}
