package org.ridewithus.domain.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "docks")
@AllArgsConstructor
@NoArgsConstructor
public class Dock {

    @Id //primary key 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by Database, not through constructors
    private Long id;

    public enum DockStatus {
        EMPTY,
        OCCUPIED,
        OUT_OF_SERVICE
    }

    @OneToOne(mappedBy = "dock")
    private Bike bike;

    @Enumerated(EnumType.STRING)
    private DockStatus status;

    @ManyToOne
    @JoinColumn(name = "station_id", nullable = false) //station_id cannot be null
    private Station station;

    public Dock(DockStatus status, Station station) {
        this.status = status;
        this.station = station;
    }

    public boolean hasActiveReservation() {
        return bike.getStatus() == BikeStatus.RESERVED;
    }
}
