package org.ridewithus.domain.entity;


import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "docks")
public class Dock {
    @Id //primary key 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by Database, not through constructors
    private Long id;



    public enum DockStatus {
        EMPTY,
        OCCUPIED,
        OUT_OF_SERVICE
    }
    @Enumerated(EnumType.STRING)
    private DockStatus status;

    @ManyToOne
    @JoinColumn(name = "station_id", nullable = false) //station_id cannot be null
    private Station station;

    @OneToMany(mappedBy = "dock")
    private List<Bike> bikes;

    public Dock() {
    }

    public Dock(DockStatus status, Station station) {
        this.status = status;
        this.station = station;
    }

    // Getters
    public Long getId() {
        return id;
    }
    public DockStatus getStatus() {
        return status;
    }
    public Station getStation() {
        return station;
    }
    public List<Bike> getBikes() {return bikes;}

    // Setters
    public void setId(Long id) {
        this.id = id;
    }
    public void setStatus(DockStatus status) {
        this.status = status;
    }
    public void setStation(Station station) {
        this.station = station;
    }
    public void setBikes(List<Bike> bikes) {this.bikes = bikes;}

    public boolean hasActiveReservation() {
        return bikes.stream().anyMatch(bike -> bike.getStatus() == Bike.BikeStatus.RESERVED);
    }
}
