package org.ridewithus.domain.entity;


import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "docks")
public class Dock {
    @Id //primary key 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by Database, not through constructors
    private Long id;

    public enum DockStatus {
    EMPTY,
    OCCUPIED,
    OUT_OF_SERVICE
    }   
    @Enumerated(EnumType.STRING)
    private DockStatus status;

    @ManyToOne
    @JoinColumn(name = "station_id", nullable = false) //station_id cannot be null
    private Station station;

    public Dock() {
    }

    public Dock(DockStatus status, Station station) {
        this.status = status;
        this.station = station;
    }

    // Getters
    public Long getId() {
        return id;
    }
    public DockStatus getStatus() {
        return status;
    }
    public Station getStation() {
        return station;
    }

    // Setters
    public void setId(Long id) {
        this.id = id;
    }
    public void setStatus(DockStatus status) {
        this.status = status;
    }
    public void setStation(Station station) {
        this.station = station;
    }
}
