package org.ridewithus.domain.entity;

import org.ridewithus.domain.loyaltyProgram.ChainOfR.Tier;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@Entity
@Table(name = "users")
@AllArgsConstructor
public class User {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by Database, not through constructors
    private Long id;

    private String fullName;
    private String userName;
    private String address;
    private String email;  
    private String role = "rider"; //user are automatically user unless specified otherwise
    private String password;


    @Column(name = "flex_dollar_balance", nullable = false)
    private int flex_dollar_balance = 0 ;

    // convenience helpers for working with flex dollars
    public int getFlexDollars() {
        return flex_dollar_balance;
    }

    public void setFlexDollars(int flexDollars) {
        this.flex_dollar_balance = flexDollars;
    }

    /**
     * Apply (deduct) flex dollars from the user's balance.
     * Will not go below zero.
     * @param amount the amount to deduct
     * @return the amount actually deducted
     */

    //ADD PAYMENT INFO OR CREATE A NEW TABLE??
    @ManyToOne
    @JoinColumn(name = "pricing_plan_id", nullable = true)
    private PricingPlan pricingPlan;

    @Enumerated(EnumType.STRING)
    @Column(name = "loyalty_tier")
    private Tier loyaltyTier;

    @Enumerated(EnumType.STRING)
    @Column(name = "prev_loyalty_tier")
    private Tier prevLoyaltyTier;

    public User() {}

    public User(String fullName, String userName, String address, String email, String password){
        this.fullName = fullName;
        this.userName = userName;
        this.address = address;
        this.email = email;
        this.password = password;
        this.role = "rider" ;  //ensures user is a rides
    }

    // when manually entering users, use this one to allow operator role
    public User(String fullName, String userName, String address, String email, String role, String password){
        this.fullName = fullName;
        this.userName = userName;
        this.address = address;
        this.email = email;
        this.password = password;
        this.role = role;
    }
}
