package org.ridewithus.domain.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "users")
public class User {
    
    @Id //primary key 
    @GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by Database, not through constructors
    private Long id;

    private String fullName;
    private String userName;
    private String address;
    private String email;  
    private String role = "rider"; //user are automatically user unless specified otherwise
    private String password ;

    //ADD PAYMENT INFO OR CREATE A NEW TABLE??

    public User() {}

    public User(String fullname, String userName, String address, String email, String password){
        this.fullName = fullname ;
        this.userName = userName ;
        this.address = address ;
        this.email = email ;
        this.password = password ;
        this.role = "rider" ;  //ensures user is a rides
    }

    // when manually entering users, use this one to allow operator role
    public User(String fullname, String userName, String address, String email, String role, String password){
        this.fullName = fullname ;
        this.userName = userName ;
        this.address = address ;
        this.email = email ;
        this.password = password ;
        this.role = role ; 
    }

    // Getters
    public String getFullName(){
        return this.fullName ;
    }
    public String getUserName(){
        return this.userName ;
    }
    public String getAddress(){
        return this.address ;
    }
    public String getEmail(){
        return this.email ;
    }
    public String getPassword(){
        return this.password ;
    }
    public String getRole(){
        return this.role;
    }

    // Setters
    public void setFullName(String name){
        this.fullName = name;
    }
    public void setUserName(String username){
        this.userName = username;
    }
    public void setAddress(String address){
        this.address = address;
    }
    public void setEmail(String email){
        this.email = email;
    }
}
