# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ridewithus_dev
    username: postgres
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

