name: Backend CI

on:
  pull_request:
    branches: [ main, phase* ]

defaults:
  run:
    working-directory: backend  # change if your pom.xml lives elsewhere

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
          cache: maven

      - name: Verify project structure
        run: ls -1

      - name: Build with Maven
        run: mvn -B clean install

      # If you prefer not to use defaults, replace the above step with:
      # - name: Build with Maven
      #   run: mvn -B -f backend/pom.xml clean install
