name: Maven PR build

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build backend with Maven (format + build)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Cache Maven repository (fallback)
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-


      - name: Build backend (mvn clean install)
        run: mvn -B -f src/backend/pom.xml clean install
